apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients
  namespace: pizza
spec:
  selector:
    matchLabels:
      app: ingredients
  template:
    metadata:
      labels:
        app: ingredients
    spec:
      containers:
      - name: ingredients
        image: local/ingredients
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ingredients
  namespace: pizza
spec:
  selector:
    app: ingredients
  ports:
  - port: 80

