apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: pizza
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: local/orders
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: pizza
spec:
  selector:
    app: orders
  ports:
  - port: 80

